on:
  [workflow_dispatch]

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push flask Docker image
        working-directory: backend
        run: |
          docker build -f Dockerfile -t ${{ vars.DOCKERHUB_USERNAME }}/flask_mediainsight .

      - name: Push Docker images
        run: |
          docker push ${{ vars.DOCKERHUB_USERNAME }}/flask_mediainsight
